name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Optional, allows manual trigger from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out your repository code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Adjust the version as per your requirement
    
    - name: Setup Artifact
      run: curl -fsSL https://github.com/actions/upload-artifact/releases/latest # Dowloads artifact

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies
      run: |
        poetry install  # Install dependencies defined in pyproject.toml

    - name: Run Tests with JUnit XML output
      run: |
        poetry run pytest --maxfail=1 --disable-warnings --junitxml=test-results/test-results.xml  # Output test results to XML

    - name: Upload Test Results
      if: failure()  # Upload test results only if the tests fail
      uses: actions/upload-artifact@v2  # Correct version to use
      with:
        name: test-results
        path: test-results/test-results.xml  # Path to the test result XML file
