name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Adjust this based on your Python version

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies
      run: |
        poetry install  # Install project dependencies using Poetry

    - name: Run Tests
      run: |
        poetry run pytest  # Run tests with pytest inside the Poetry virtual environment

    - name: Upload Test Results (optional)
      if: failure()  # Only upload results if the tests fail
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results/  # Adjust the path to your test results directory if needed
